// <auto-generated />
using System;
using DL.DatabaseContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DL.DatabaseContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191020185101_InsertData")]
    partial class InsertData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DL.DomainModels.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<decimal>("TotalAmount");

                    b.Property<int>("Type");

                    b.Property<DateTime?>("UpdateDate");

                    b.HasKey("Id");

                    b.ToTable("Operations");

                    b.HasData(
                        new { Id = 1, Amount = 1000m, CreateDate = new DateTime(2019, 10, 20, 21, 51, 1, 23, DateTimeKind.Local), Description = "Initial Debit", TotalAmount = 1000m, Type = 1 },
                        new { Id = 2, Amount = 100m, CreateDate = new DateTime(2019, 10, 20, 21, 51, 1, 25, DateTimeKind.Local), Description = "Initial Credit", TotalAmount = 900m, Type = 2 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
